import './globals.css'
import type { Metadata } from 'next'
import { Header } from '@/layout/header/Header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='max-w-[820px] mx-auto'>
        <Header />
        {children}
      </body>
    </html>
  )
}
